In [1]:
import xarray as xr
import numpy as np
import pandas as pd

In [2]:
df_grace = xr.open_dataset('~/remoteData/GRACE_NEW/data/TELLUS_GRAC_L3_CSR_RL06_LND_v04/GRD-3_2017143-2017179_GRAC_UTCSR_BA01_0600_LND_v04.nc')

In [3]:
df_gracefo = xr.open_dataset('~/remoteData/GRACEFO/GRD-3_2018152-2018181_GRFO_UTCSR_BA01_0601_LND_v04.nc')

In [4]:
df_grace

<xarray.Dataset>
Dimensions:        (lon: 360, lat: 180, time: 1, bounds: 2)
Coordinates:
  * lon            (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 356.5 357.5 358.5 359.5
  * lat            (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
  * time           (time) datetime64[ns] 2017-06-10T12:00:00
Dimensions without coordinates: bounds
Data variables:
    lwe_thickness  (time, lat, lon) float64 ...
    uncertainty    (time, lat, lon) float64 ...
    lat_bounds     (lat, bounds) float64 ...
    lon_bounds     (lon, bounds) float64 ...
    time_bounds    (time, bounds) datetime64[ns] ...
Attributes: (12/59)
    Conventions:                CF-1.6
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    title:                      GRACE-FO Water-Equivalent-Thickness Surface-M...
    id:                         TELND-3NC64
    summary:                    Gridded surface mass anomalies, derived from ...
    processing_level:           3
    ...                         ...
    geospatial_lat_units:       degrees_north
    geospatial_lat_resolution:  One degree grid
    geospatial_lon_min:         0.5
    geospatial_lon_max:         359.5
    geospatial_lon_units:       degrees_east
    geospatial_lon_resolution:  One degree grid

In [5]:
df_grace['lwe_thickness']

<xarray.DataArray 'lwe_thickness' (time: 1, lat: 180, lon: 360)>
[64800 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * time     (time) datetime64[ns] 2017-06-10T12:00:00
Attributes:
    units:         m
    long_name:     Liquid_Water_Equivalent_Thickness
    grid_mapping:  WGS 84
    valid_min:     -30.0
    valid_max:     30.0
    comment:       none

In [35]:
df_grace['lon_bounds']

<xarray.DataArray 'lon_bounds' (lon: 360, bounds: 2)>
[720 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
Dimensions without coordinates: bounds
Attributes:
    long_name:  longitude boundaries
    units:      degrees_east
    comment:    longitude values at the west and east bounds of each pixel

In [36]:
df_grace['lat_bounds']

<xarray.DataArray 'lat_bounds' (lat: 180, bounds: 2)>
[360 values with dtype=float64]
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
Dimensions without coordinates: bounds
Attributes:
    long_name:  latitude boundaries
    units:      degrees_north
    comment:    latitude values at the north and south bounds of each pixel

In [6]:
print(df_grace['lat_bounds'].values)


[[-9.00000000e+01 -8.90000000e+01]
 [-8.90000000e+01 -8.80000000e+01]
 [-8.80000000e+01 -8.70000000e+01]
 [-8.70000000e+01 -8.60000000e+01]
 [-8.60000000e+01 -8.50000000e+01]
 [-8.50000000e+01 -8.40000000e+01]
 [-8.40000000e+01 -8.30000000e+01]
 [-8.30000000e+01 -8.20000000e+01]
 [-8.20000000e+01 -8.10000000e+01]
 [-8.10000000e+01 -8.00000000e+01]
 [-8.00000000e+01 -7.90000000e+01]
 [-7.90000000e+01 -7.80000000e+01]
 [-7.80000000e+01 -7.70000000e+01]
 [-7.70000000e+01 -7.60000000e+01]
 [-7.60000000e+01 -7.50000000e+01]
 [-7.50000000e+01 -7.40000000e+01]
 [-7.40000000e+01 -7.30000000e+01]
 [-7.30000000e+01 -7.20000000e+01]
 [-7.20000000e+01 -7.10000000e+01]
 [-7.10000000e+01 -7.00000000e+01]
 [-7.00000000e+01 -6.90000000e+01]
 [-6.90000000e+01 -6.80000000e+01]
 [-6.80000000e+01 -6.70000000e+01]
 [-6.70000000e+01 -6.60000000e+01]
 [-6.60000000e+01 -6.50000000e+01]
 [-6.50000000e+01 -6.40000000e+01]
 [-6.40000000e+01 -6.30000000e+01]
 [-6.30000000e+01 -6.20000000e+01]
 [-6.20000000e+01 -6

In [9]:
print(df_grace['lat_bounds'].coords)

Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5


In [11]:
df_grace['lat_bounds'].sel(lat=-89.5).values

array([-90., -89.])

In [8]:
print(df_grace['lwe_thickness'].dims)

('time', 'lat', 'lon')


In [13]:
print(df_grace['lwe_thickness'].coords)

Coordinates:
  * lon      (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * time     (time) datetime64[ns] 2017-06-10T12:00:00


In [18]:
print(df_grace['lwe_thickness'].values)

[[[-2.52981349e-03 -2.50985942e-03 -2.49027531e-03 -2.47104883e-03
   -2.45216799e-03 -2.43362117e-03 -2.41539707e-03 -2.39748477e-03
   -2.37987372e-03 -2.36255378e-03 -2.34551517e-03 -2.32874856e-03
   -2.31224502e-03 -2.29599605e-03 -2.27999361e-03 -2.26423011e-03
   -2.24869843e-03 -2.23339195e-03 -2.21830453e-03 -2.20343055e-03
   -2.18876492e-03 -2.17430310e-03 -2.16004110e-03 -2.14597550e-03
   -2.13210346e-03 -2.11842278e-03 -2.10493183e-03 -2.09162966e-03
   -2.07851594e-03 -2.06559102e-03 -2.05285593e-03 -2.04031239e-03
   -2.02796284e-03 -2.01581044e-03 -2.00385909e-03 -1.99211343e-03
   -1.98057887e-03 -1.96926160e-03 -1.95816857e-03 -1.94730755e-03
   -1.93668708e-03 -1.92631652e-03 -1.91620604e-03 -1.90636661e-03
   -1.89681002e-03 -1.88754887e-03 -1.87859658e-03 -1.86996736e-03
   -1.86167623e-03 -1.85373900e-03 -1.84617225e-03 -1.83899336e-03
   -1.83222042e-03 -1.82587230e-03 -1.81996857e-03 -1.81452948e-03
   -1.80957599e-03 -1.80512967e-03 -1.80121274e-03 -1.79784798

In [21]:
df_grace['lwe_thickness'].sel(lon=0.5, lat = -89.5).values

array([-0.00252981])

In [22]:
df_grace['lwe_thickness'].sel(lon=0.5, lat = -89.6).values

KeyError: "not all values found in index 'lat'. Try setting the `method` keyword argument (example: method='nearest')."

In [25]:
lwe_thickness = df_grace['lwe_thickness']

lat: 30N-40N, lon: 90W-80W (-90to-80)

lat: 30-40, lon:270-280

In [26]:
lwe_thickness

<xarray.DataArray 'lwe_thickness' (time: 1, lat: 180, lon: 360)>
[64800 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * time     (time) datetime64[ns] 2017-06-10T12:00:00
Attributes:
    units:         m
    long_name:     Liquid_Water_Equivalent_Thickness
    grid_mapping:  WGS 84
    valid_min:     -30.0
    valid_max:     30.0
    comment:       none

In [27]:
lwe_thickness.sel(time='2017-06-10T12:00:00.000000000', lat=3.5, lon=0.5)

KeyError: "not all values found in index 'lat'. Try setting the `method` keyword argument (example: method='nearest')."

In [28]:
df_gracefo

<xarray.Dataset>
Dimensions:        (lon: 360, lat: 180, time: 1, bounds: 2)
Coordinates:
  * lon            (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 356.5 357.5 358.5 359.5
  * lat            (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
  * time           (time) datetime64[ns] 2018-06-16
Dimensions without coordinates: bounds
Data variables:
    lwe_thickness  (time, lat, lon) float64 ...
    uncertainty    (time, lat, lon) float64 ...
    lat_bounds     (lat, bounds) float64 ...
    lon_bounds     (lon, bounds) float64 ...
    time_bounds    (time, bounds) datetime64[ns] ...
Attributes: (12/59)
    Conventions:                CF-1.6
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    title:                      GRACE-FO Water-Equivalent-Thickness Surface-M...
    id:                         TELND-3NC64
    summary:                    Gridded surface mass anomalies, derived from ...
    processing_level:           3
    ...                         ...
    geospatial_lat_units:       degrees_north
    geospatial_lat_resolution:  One degree grid
    geospatial_lon_min:         0.5
    geospatial_lon_max:         359.5
    geospatial_lon_units:       degrees_east
    geospatial_lon_resolution:  One degree grid

In [29]:
df_gracefo['lwe_thickness']

<xarray.DataArray 'lwe_thickness' (time: 1, lat: 180, lon: 360)>
[64800 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * time     (time) datetime64[ns] 2018-06-16
Attributes:
    units:         m
    long_name:     Liquid_Water_Equivalent_Thickness
    grid_mapping:  WGS 84
    valid_min:     -30.0
    valid_max:     30.0
    comment:       none

In [43]:
df_grace['lat_bounds'].sel(lat=1.5).values

KeyError: "not all values found in index 'lat'. Try setting the `method` keyword argument (example: method='nearest')."

In [42]:
df_grace['lon_bounds'].sel(lon=3, method='nearest').values

array([3., 4.])

In [ ]:
xr.DataArray()